### ISSUE TITLE
"Description Resource Path Location Type FindOAuthConsumerIfTokenIsValid cannot be resolved to a type	OAuth2TokenValidationService.java"

### ISSUE THREAD

**Issue by ghost** [angel-git/wso2is-springoauth#1]
I'm facing following problem. Please help me out
Description Resource    Path    Location    Type
The method getFindOAuthConsumerIfTokenIsValidResponse(String) from the type OAuth2TokenValidationService refers to the missing type FindOAuthConsumerIfTokenIsValidResponse OAuth2TokenValidationService.java   /yenlo-oauth/src/main/java/com/yenlo/oauth/token/ws line 22 Java Problem

**Comment by angel-git** [comment]
when do you have that problem? have you built with maven?

**Comment by ghost** [comment]
Yes, I've just perform mvn clean, mvn compile and mvn install. The above error gone, now it's giving

"Errors occurred during the build.Errors running builder 'Maven Project Builder' on project 'yenlo-oauth'.java.lang.AssertionError".

**Comment by angel-git** [comment]
you need to use maven 3. Check: **mvn -version**

**Comment by ghost** [comment]
I'm already using the maven-3:
$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-36-generic", arch: "amd64", family: "unix"

**Comment by angel-git** [comment]
do you build from Eclipse or from command line? can you try to build from the command line: **mvn clean install** ?

**Comment by ghost** [comment]
I've resolved this issue. Thanks
