### ISSUE TITLE
WSO2 PlayGround Code not working, compilation problem

### ISSUE THREAD

**Issue by ghost** [angel-git/wso2is-springoauth#3]
Looking forward to implement code present in the following SVN repository
https://svn.wso2.org/repos/wso2/carbon/platform/branches/turing/products/is/5.0.0/modules/samples/
but see some compilation issue. 
No marketplace entries found to handle incremental-build-plugin:1.3:incremental-build in Eclipse.  Please see Help for more information.
Could you please check?

**Comment by angel-git** [comment]
It looks like you have issues with wso2. Please use their ticket system to open issues on their repository. Hence closing the issue.
