### ISSUE TITLE
compilation issue for xjc

### ISSUE THREAD

**Issue by ghost** [angel-git/wso2is-springoauth#5]
I'm getting error

Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed: A required class was missing 
 while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate: com/sun/xml/bind/api/ErrorListener 
 ----------------------------------------------------- realm = plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3 
 strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy urls[0] = file:/C:/Users/prateek/.m2/repository/org/
 jvnet/jaxb2/maven2/maven-jaxb2-plugin/0.12.3/maven-jaxb2-plugin-0.12.3.jar urls[1] = file:/C:/Users/prateek/.m2/
 repository/org/jvnet/jaxb2/maven2/maven-jaxb2-plugin-core/0.12.3/maven-jaxb2-plugin-core-0.12.3.jar urls[2] = file:/C:/
 Users/prateek/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar urls[3] = file:/C:/Users/prateek/.m2/repository/org/
 apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar urls[4] = file:/C:/Users/prateek/.m2/repository/com/
 sun/org/apache/xml/internal/resolver/20050927/resolver-20050927.jar urls[5] = file:/C:/Users/prateek/.m2/repository/
 junit/junit/4.8.1/junit-4.8.1.jar urls[6] = file:/C:/Users/prateek/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/
 plexus-utils-1.5.15.jar urls[7] = file:/C:/Users/prateek/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb22-plugin/
 0.12.3/maven-jaxb22-plugin-0.12.3.jar urls[8] = file:/C:/Users/prateek/.m2/repository/org/glassfish/jaxb/jaxb-runtime/
 2.2.11/jaxb-runtime-2.2.11.jar urls[9] = file:/C:/Users/prateek/.m2/repository/org/glassfish/jaxb/jaxb-xjc/2.2.11/jaxb-
 xjc-2.2.11.jar urls[10] = file:/C:/Users/prateek/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-
 annotations/3.2/maven-plugin-annotations-3.2.jar Number of foreign imports: 5 import: Entry[import 
 org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]] import: Entry[import from 
 realm ClassRealm[maven.api, parent: null]] ----------------------------------------------------- 
 (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate:default:generate-sources)

**Comment by angel-git** [comment]
This repository does not fail while compiling, if you are having problems with custom code, please use the proper forum. This is not the place.

**Comment by ghost** [comment]
No, I'm not using any custom code. Only I'm trying to compile it and facing with the above errors. Anyway I will try to fix it.
